default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  username: vagrant
  password: vagrant
  host: localhost

development:
  <<: *default
  database: measureit_development

test:
  <<: *default
  database: measureit_test

production:
  <<: *default
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
